require 'pomo'
require 'pathname'

class TranslationObject
  attr_accessor :msgid, :msgstr

  def initialize(msgid, msgstr)
    self.msgid = msgid
    self.msgstr = msgstr
  end

  def plural?
    false
  end

  def comment
    ''
  end
end

module Action
  class ExportGettext
#TODO: project based
    def initialize(project_id, language_iso_code)
      @project = Project.find(project_id)
      @language = Language.find_by_iso_code!(language_iso_code)
    end

    def get_gettext
      header + Pomo::PoFile.to_text(translations)
    end

    def header
      content = <<-T7E
# This file is generated by t7e
# for more information https://github.com/visualitypl/t7e
#
#
#


      T7E
    end

    private

    def translations
      data = []
      @project.translation_entries.gettext.each do |entry|
        value = (Translation.where(translation_entry: entry, language: @language).first.try(:value) ||'')
        data << TranslationObject.new(entry.path, value)
      end

      return data
    end
  end
end